### ISSUE TITLE
SECRETS_YAML_ENVIRONMENT injects no environment variables

### ISSUE THREAD

**Issue by mkkeffeler** [cyberark/cloudfoundry-conjur-buildpack#128]
## Summary
I was using the environment functionality and my app failed to deploy.

## Steps to Reproduce

Deployed java app with this secrets.yml

```
dv:
  CyberArk_user: 'cyberark-api-a'
  CyberArk_pass: 'test
qa:
  CyberArk_user: 'cyberark-api-a'
  CyberArk_pass: 'test'
st:
  CyberArk_user: 'cyberark-api-a'
  CyberArk_pass: 'test'
pr:
  CyberArk_user: !var AZ/real/var/username
  CyberArk_pass: !var AZ/real/var/password
```
And set in the manifest  ```SECRETS_YAML_ENVIRONMENT=dv```

app failed to start, couldn't find ```CyberArk_pass``` (logs attached).

Changed Secrets.yml to 

```
  CyberArk_user: 'cyberark-api-a'
  CyberArk_pass: 'test'
```
And deployed no issues (logs attached).

I also tried setting the ```common``` section, still no luck.

## Expected Results
I should have had the environment vars in section dv and common get set.

## Actual Results (including error logs, if applicable)
They were not set properly, and logs don't show an rror.
## Reproducible
   * [ X] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
cyberark-conjur-buildpack-v1.2.1.zip

## Environment setup
Container, PCF

## Additional Information
NA
[healthylogs.txt](https://github.com/cyberark/cloudfoundry-conjur-buildpack/files/6788761/healthylogs.txt)
[failurelogs.txt](https://github.com/cyberark/cloudfoundry-conjur-buildpack/files/6788762/failurelogs.txt)
