### ISSUE TITLE
Buildpack uses `profile.d` directory

### ISSUE THREAD

**Issue by micahlee** [cyberark/cloudfoundry-conjur-buildpack#22]
There are couple of buildpack issues to address after incorporating the buildpack in the Conjur service broker demo:

* The supply script should be placed in the directory `profile.d`, rather than `.profile.d`
    > https://github.com/cyberark/cloudfoundry-conjur-buildpack/blob/7bccc304902c26dafa8e30a9318dbe789ea48907/bin/supply#L30-L38

* The readme should use underscores in the buildpack names rather than dashes:
    ```
    cf push my-app -b conjur_buildpack -b final_buildpack
    ```

* The readme should include an example of using the buildpack in the manifest:
    ```
    ---
    applications:
    - name: my-app
      services:
      - conjur
      buildpacks:
      - conjur_buildpack
      - final_buildpack
    ```
