### ISSUE TITLE
Add support for Summon environments

### ISSUE THREAD

**Issue by izgeri** [cyberark/cloudfoundry-conjur-buildpack#44]
Summon supports an [`environment` flag](https://github.com/cyberark/summon/#flags) which allows you to specify different variables for different app environments (eg dev, prod, etc)

The secrets.yml syntax in that case would look something like this:
```
common:
  ACCOUNT: my-account
  SHARED_PASSWORD: SuperSecret

dev:
  CLUSTER_NAME: !var dev/cluster-name
  ZONE: !var dev/zone

prod:
  CLUSTER_NAME: !var prod/cluster-name
  ZONE: !var prod/zone
```
where the variables in `common` are loaded regardless of environment and the variables in `dev` / `prod` are only loaded when the environment specified is `dev` or `prod` (respectively).

The buildpack should support an environment variable (perhaps `SUMMON_ENV_KEY_NAME` as [here](https://github.com/cyberark/summon/blob/master/internal/command/action.go#L138)?) that allows the user to specify the value of `environment` the buildpack should use to load the correct variables for the app env.
